import sys
import json
from fpdf import FPDF
from datetime import datetime

def generate_report(job_id, media_name, result, output_path):
    pdf = FPDF()
    pdf.add_page()
    
    # Header
    pdf.set_font("Arial", "B", 24)
    pdf.set_text_color(7, 17, 31) # Dark Navy
    pdf.cell(0, 20, "FakeShield AI - Forensic Report", 0, 1, "C")
    
    pdf.set_font("Arial", "", 10)
    pdf.set_text_color(100, 100, 100)
    pdf.cell(0, 10, f"Report ID: FS-RPT-{job_id}-{int(datetime.now().timestamp())}", 0, 1, "C")
    pdf.ln(10)
    
    # Media Info
    pdf.set_font("Arial", "B", 14)
    pdf.set_text_color(0, 0, 0)
    pdf.cell(0, 10, "Media Information", 0, 1)
    pdf.set_font("Arial", "", 12)
    pdf.cell(0, 10, f"File Name: {media_name}", 0, 1)
    pdf.cell(0, 10, f"Analysis Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", 0, 1)
    pdf.ln(5)
    
    # Executive Summary
    pdf.set_font("Arial", "B", 14)
    pdf.cell(0, 10, "Executive Summary", 0, 1)
    
    risk_level = result.get('riskLevel', 'low')
    risk_colors = {
        'critical': (239, 68, 68),
        'high': (249, 115, 22),
        'moderate': (245, 158, 11),
        'low': (16, 185, 129)
    }
    color = risk_colors.get(risk_level, (16, 185, 129))
    
    pdf.set_font("Arial", "B", 12)
    pdf.set_text_color(*color)
    pdf.cell(0, 10, f"Authenticity Score: {result.get('authenticityScore', 0)}% ({risk_level.upper()} RISK)", 0, 1)
    
    pdf.set_font("Arial", "", 11)
    pdf.set_text_color(0, 0, 0)
    pdf.multi_cell(0, 8, result.get('summary', ''))
    pdf.ln(10)
    
    # Forensic Signals
    pdf.set_font("Arial", "B", 14)
    pdf.cell(0, 10, "Forensic Signals & Anomalies", 0, 1)
    
    for signal in result.get('signals', []):
        pdf.set_font("Arial", "B", 11)
        pdf.cell(0, 8, f"{signal.get('type', 'Unknown')} (Anomaly Score: {signal.get('score', 0)}%)", 0, 1)
        pdf.set_font("Arial", "", 10)
        pdf.multi_cell(0, 6, signal.get('description', ''))
        pdf.ln(4)
    
    # Footer
    pdf.set_y(-30)
    pdf.set_font("Arial", "I", 8)
    pdf.set_text_color(150, 150, 150)
    pdf.cell(0, 10, "This report was generated by FakeShield AI Forensic Engine. Results are probabilistic.", 0, 0, "C")
    
    pdf.output(output_path)

if __name__ == "__main__":
    job_id = sys.argv[1]
    media_name = sys.argv[2]
    result_json = sys.argv[3]
    output_path = sys.argv[4]
    
    result = json.loads(result_json)
    generate_report(job_id, media_name, result, output_path)
